# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-2022

variables:
  buildConfiguration: 'Release'

steps:


- task: DotNetCoreCLI@2
  displayName: 'Build $(buildConfiguration)'
  inputs:
    command: 'build'
    workingDirectory: 'src/'
    projects: '**/*.csproj'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Unit Test 
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    configuration: $(buildConfiguration)
    testRunTitle: 'project tests run'
    workingDirectory: 'test/'
    
- task: DotNetCoreCLI@2
  displayName: Publish Artifacts
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: 'src/'

    # Publish Project Zip Folders
- task: PublishBuildArtifacts@1
  displayName: Publish Project Zip Folders
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact'
    publishLocation: 'Container'

# Publish ARM Templates
- task: CopyFiles@2
  displayName: Copy ARM templates
  inputs:
    SourceFolder: 'templates'
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/artifact/templates/'
    CleanTargetFolder: true





    