parameters:
  azureResourceManagerConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  artifactFolder: '$(Pipeline.Workspace)/package_build/armTemplates/'
  location: ''
  loggingLevel: ''

steps:
- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: CmdLine@2
    displayName: "[Debug] Output artifact structure"
    inputs:
      script: 'ls -R ${{parameters.artifactFolder}}'

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: Replace Tokens in ARM template
  inputs:
    rootDirectory: '${{parameters.artifactFolder}}'
    targetFiles: '*.json'
    encoding: 'auto'
    writeBOM: true
    verbosity: 'detailed'
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

# Show ARM template & parameter values before deployment
- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: PowerShell@2
    displayName: '[Debug] Output ARM templates that will be deployed'
    inputs:
      targetType: inline
      script: |
        $files = Get-ChildItem -Path ${{parameters.artifactFolder}}\*.json
        foreach ($file in $files)
        {
          Write-Host "=== ARM template Output ==="
          Write-Host "Filename: ($file)" 
          $content = Get-Content $file
          Write-Host $content
        }

# Deploy Components through ARM

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Key Vault on ${{parameters.resourceGroupName}}'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '${{parameters.azureResourceManagerConnection}}'
    subscriptionId: '${{parameters.subscriptionId}}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{parameters.resourceGroupName}}'
    location: '${{parameters.location}}'
    templateLocation: 'Linked artifact'
    csmFile: '${{parameters.artifactFolder}}/0_1KeyVault.json'
    csmParametersFile: '${{parameters.artifactFolder}}/0_1KeyVault.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'ArmOutputs'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy App Service Plan on ${{parameters.resourceGroupName}}'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '${{parameters.azureResourceManagerConnection}}'
    subscriptionId: '${{parameters.subscriptionId}}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{parameters.resourceGroupName}}'
    location: '${{parameters.location}}'
    templateLocation: 'Linked artifact'
    csmFile: '${{parameters.artifactFolder}}/1AppServicePlan.json'
    csmParametersFile: '${{parameters.artifactFolder}}/1AppServicePlan.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'ArmOutputs'
