parameters:
  azureResourceManagerConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  armArtifactFolder: '$(Pipeline.Workspace)/package_build/armTemplates/'
  location: ''
  databaseName: ''
  loggingLevel: ''

steps:
#- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
#  - task: PowerShell@2
#    displayName: "[Debug] Output artifact structure"
#    inputs:
#      targetType: inline
#      script:  |
#        'ls -R ${{parameters.armArtifactFolder}}'
#        'ls -R ${{parameters.sqlArtifactFolder}}'

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: Replace Tokens in ARM template
  inputs:
    rootDirectory: '${{parameters.armArtifactFolder}}'
    targetFiles: '*.json'
    encoding: 'auto'
    writeBOM: true
    verbosity: 'detailed'
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

# Show ARM template & parameter values before deployment
- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: PowerShell@2
    displayName: '[Debug] Output ARM templates that will be deployed'
    inputs:
      targetType: inline
      script: |
        $files = Get-ChildItem -Path ${{parameters.armArtifactFolder}}\*.json
        foreach ($file in $files)
        {
          Write-Host "=== ARM template Output ==="
          Write-Host "Filename: ($file)" 
          $content = Get-Content $file
          Write-Host $content
        }

# Deploy Infra Components through ARM

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Key Vault on ${{parameters.resourceGroupName}}'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '${{parameters.azureResourceManagerConnection}}'
    subscriptionId: '${{parameters.subscriptionId}}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{parameters.resourceGroupName}}'
    location: '${{parameters.location}}'
    templateLocation: 'Linked artifact'
    csmFile: '${{parameters.armArtifactFolder}}/1KeyVault.json'
    csmParametersFile: '${{parameters.armArtifactFolder}}/1KeyVault.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'ArmOutputs'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Application on ${{parameters.resourceGroupName}}'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '${{parameters.azureResourceManagerConnection}}'
    subscriptionId: '${{parameters.subscriptionId}}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{parameters.resourceGroupName}}'
    location: '${{parameters.location}}'
    templateLocation: 'Linked artifact'
    csmFile: '${{parameters.armArtifactFolder}}/2WebApp-SQLDatabase-AppPlan-AI.json'
    csmParametersFile: '${{parameters.armArtifactFolder}}/2WebApp-SQLDatabase-AppPlan-AI.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'AppOutputs'