parameters:
  azureResourceManagerConnection: ''
  AppArtifactFolder: '$(Pipeline.Workspace)/package_build/sourceZips/'


steps:
# Deploy WebApp on AppService

- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: CmdLine@2
    displayName: "[Debug] Output artifact structure"
    inputs:
      script: 'ls -R ${{parameters.AppArtifactFolder}}'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '${{parameters.azureResourceManagerConnection}}'    
    appType: 'webApp'
    appName: $(AppOutputs.WebAppName.value)
    package: '${{parameters.AppArtifactFolder}}/*.zip'