parameters:
  svcname: ''
  appService: ''
  AppArtifactFolder: '$(Pipeline.Workspace)/package_build/sourceZips/'


steps:
# Deploy WebApp on AppService

- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: CmdLine@2
    displayName: "[Debug] Output artifact structure"
    inputs:
      script: 'ls -R ${{parameters.AppArtifactFolder}}'

- task: AzureWebApp@1
  displayName: Deploy Web Api on ${{parameters.appName}}
  inputs:
    azureSubscription: ${{parameters.svcname}}
    appType: 'webApp'
    appName: ${{parameters.appService}}
    package: '${{parameters.AppArtifactFolder}}/*.zip'