parameters:
  azureResourceManagerConnection: ''
  DatabaseName: ''
  location: ''
  loggingLevel: ''
  sqlArtifactFolder: '$(Pipeline.Workspace)/package_build/sqlMigrations'

stages:

- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: CmdLine@2
    displayName: "[Debug] Output artifact structure"
    inputs:
      script: 'ls -R ${{parameters.sqlArtifactFolder}}'

# Run initial SQL script
- task: SqlAzureDacpacDeployment@1
  displayName: Run initial SQL script
  inputs:
    azureSubscription: '${{parameters.azureResourceManagerConnection}}'
    AuthenticationType: 'servicePrincipal'
    ServerName: '$(AppOutputs.sqlServerName.value)'
    DatabaseName: '${{parameters.DatabaseName}}'
    deployType: 'SqlTask'
    SqlFile: '${{parameters.artifactFolder}}/Initial.sql'
    IpDetectionMethod: 'AutoDetect'