parameters:
  serviceName: ''
  databaseName: ''
  location: ''
  loggingLevel: ''
  tmpFolder: 'C:\Users\VssAdministrator\AppData\Local\Temp'
  sqlArtifactFolder: '$(Pipeline.Workspace)/package_build/sqlMigrations'

steps:

- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: CmdLine@2
    displayName: "[Debug] Output artifact structure"
    inputs:
      script: 'ls -R ${{parameters.sqlArtifactFolder}}'

# Run initial SQL script
- task: AzureKeyVault@2
  displayName: Get Credentials for Db script
  inputs:
    azureSubscription: '${{parameters.serviceName}}'
    KeyVaultName: '${{parameters.keyVaultName}}'    
    SecretsFilter: 'CarsApiSQLAdminUsername,CarsApiSQLAdminPassword'
    RunAsPreJob: false

- ${{ if eq(parameters.loggingLevel, 'Debug') }}:
  - task: CmdLine@2
    displayName: "[Debug] Output tmp folder"
    inputs:
      script: 'ls -R ${{parameters.tmpFolder}}'

- task: SqlAzureDacpacDeployment@1
  displayName: Run initial Sql sheet
  inputs:
    azureSubscription: '${{parameters.servicename}}'
    AuthenticationType: 'server'
    ServerName: '$(AppOutputs.sqlServerName.value)'
#    DatabaseName: 'carsdb'
    SqlUsername: $(CarsApiSQLAdminUsername)
    SqlPassword: $(CarsApiSQLAdminPassword)
    deployType: 'SqlTask'
    SqlFile: '${{parameters.sqlArtifactFolder}}/initial.sql'
    IpDetectionMethod: 'AutoDetect'