trigger: none

variables:
  System.Debug: False
  Release.ReleaseName: $(Build.BuildNumber)
  Release.Deployment.RequestedFor: $(Build.QueuedBy)

name: CarsAPI.App-$(Date:yyyyMMdd)$(Rev:.r)

stages:
  - template: build-template.yml
  - template: release-template.yml