# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
- group: Azure.Infrastructure
- group: CarsApi.Infra.Dev

stages:
- stage: Deploy_ARM_templates
  displayName: Download_ARM_Templates

  jobs:
  - deployment: Deploy_ARM_templates
    displayName: Deploy_ARM_Templates
    environment: $(Infra.Environment.Name)
    pool:
      vmImage: $(vmImage.Name)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: DownloadBuildArtifacts@1
            displayName: Download ARM Templates
            inputs:
              buildType: 'current'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'Templates/0ResourceGroup_StorageAccount'
              downloadPath: $(ARM.Template.WD)